# Generated by Django 2.2.5 on 2022-12-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_auto_20221206_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Doctor_Middlename',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='ID',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='IIN',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='doctor',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='degree',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='exp_years',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='photo_URI',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='price_of_appointment',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='rating',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='ID',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='IIN',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='patient',
            name='Patient_Middle_Name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
