# Generated by Django 2.2.5 on 2022-12-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_auto_20221206_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(choices=[('A', 'A'), ('AB', 'AB'), ('B', 'B'), ('O', 'O')], max_length=3),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('Married', 'Married'), ('Single', 'Single'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], default='-', max_length=20),
        ),
    ]
