# Generated by Django 2.2.5 on 2022-12-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_auto_20221206_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='degree',
            field=models.CharField(choices=[('Professional Doctorate', 'Professional Doctorate'), ('Clinical Doctorate', 'Clinical Doctorate'), ('Research Doctorate', 'Research Doctorate')], default=' ', max_length=50),
        ),
    ]
