# Generated by Django 2.2.5 on 2022-12-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_auto_20221206_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='accstatus',
            field=models.BooleanField(default=False),
        ),
    ]
