# Generated by Django 2.2.5 on 2022-12-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0011_auto_20221207_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(default='media/patientLogin.png', upload_to='image'),
        ),
    ]
