# Generated by Django 2.2.5 on 2022-12-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0012_doctor_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(default='image/default.png', upload_to='image/'),
        ),
    ]
