# Generated by Django 2.2.5 on 2022-12-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0015_auto_20221207_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='photo',
        ),
        migrations.AddField(
            model_name='doctor',
            name='photo_URI',
            field=models.CharField(default='', max_length=100),
        ),
    ]
