# Generated by Django 2.2.5 on 2022-12-08 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0016_auto_20221207_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.Doctor'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='photo_URI',
            field=models.CharField(default='/image/default.png', max_length=100),
        ),
    ]
